// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneof.proto

package org.apache.flink.formats.protobuf.testproto;

public interface OneofTestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.apache.flink.formats.protobuf.proto.OneofTest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 a = 1;</code>
   */
  boolean hasA();
  /**
   * <code>optional int32 a = 1;</code>
   */
  int getA();

  /**
   * <code>optional int32 b = 2;</code>
   */
  boolean hasB();
  /**
   * <code>optional int32 b = 2;</code>
   */
  int getB();

  public org.apache.flink.formats.protobuf.testproto.OneofTest.TestOneofCase getTestOneofCase();
}
