// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/protobufTest.proto

package io.pravega.connectors.flink.formats.registry.testProto;

public interface InternalMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.pravega.connectors.flink.formats.registry.testProto.InternalMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values value = 1;</code>
   * @return The enum numeric value on the wire for value.
   */
  int getValueValue();
  /**
   * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values value = 1;</code>
   * @return The value.
   */
  io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values getValue();
}
