// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/protobufTest.proto

package io.pravega.connectors.flink.formats.registry.testProto;

/**
 * Protobuf type {@code io.pravega.connectors.flink.formats.registry.testProto.InternalMessage}
 */
public final class InternalMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.pravega.connectors.flink.formats.registry.testProto.InternalMessage)
    InternalMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InternalMessage.newBuilder() to construct.
  private InternalMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InternalMessage() {
    value_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InternalMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InternalMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            value_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.pravega.connectors.flink.formats.registry.testProto.ProtobufTest.internal_static_io_pravega_connectors_flink_formats_registry_testProto_InternalMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.pravega.connectors.flink.formats.registry.testProto.ProtobufTest.internal_static_io_pravega_connectors_flink_formats_registry_testProto_InternalMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.class, io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Builder.class);
  }

  /**
   * Protobuf enum {@code io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values}
   */
  public enum Values
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>val1 = 0;</code>
     */
    val1(0),
    /**
     * <code>val2 = 1;</code>
     */
    val2(1),
    /**
     * <code>val3 = 2;</code>
     */
    val3(2),
    /**
     * <code>val4 = 3;</code>
     */
    val4(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>val1 = 0;</code>
     */
    public static final int val1_VALUE = 0;
    /**
     * <code>val2 = 1;</code>
     */
    public static final int val2_VALUE = 1;
    /**
     * <code>val3 = 2;</code>
     */
    public static final int val3_VALUE = 2;
    /**
     * <code>val4 = 3;</code>
     */
    public static final int val4_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Values valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Values forNumber(int value) {
      switch (value) {
        case 0: return val1;
        case 1: return val2;
        case 2: return val3;
        case 3: return val4;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Values>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Values> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Values>() {
            public Values findValueByNumber(int number) {
              return Values.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final Values[] VALUES = values();

    public static Values valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Values(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values)
  }

  public static final int VALUE_FIELD_NUMBER = 1;
  private int value_;
  /**
   * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values value = 1;</code>
   * @return The enum numeric value on the wire for value.
   */
  @java.lang.Override public int getValueValue() {
    return value_;
  }
  /**
   * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values value = 1;</code>
   * @return The value.
   */
  @java.lang.Override public io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values getValue() {
    @SuppressWarnings("deprecation")
    io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values result = io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values.valueOf(value_);
    return result == null ? io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (value_ != io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values.val1.getNumber()) {
      output.writeEnum(1, value_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (value_ != io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values.val1.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, value_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.pravega.connectors.flink.formats.registry.testProto.InternalMessage)) {
      return super.equals(obj);
    }
    io.pravega.connectors.flink.formats.registry.testProto.InternalMessage other = (io.pravega.connectors.flink.formats.registry.testProto.InternalMessage) obj;

    if (value_ != other.value_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + value_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.pravega.connectors.flink.formats.registry.testProto.InternalMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.InternalMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.InternalMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.InternalMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.InternalMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.InternalMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.InternalMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.InternalMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.InternalMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.InternalMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.InternalMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.InternalMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.pravega.connectors.flink.formats.registry.testProto.InternalMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.pravega.connectors.flink.formats.registry.testProto.InternalMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.pravega.connectors.flink.formats.registry.testProto.InternalMessage)
      io.pravega.connectors.flink.formats.registry.testProto.InternalMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.pravega.connectors.flink.formats.registry.testProto.ProtobufTest.internal_static_io_pravega_connectors_flink_formats_registry_testProto_InternalMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.pravega.connectors.flink.formats.registry.testProto.ProtobufTest.internal_static_io_pravega_connectors_flink_formats_registry_testProto_InternalMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.class, io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Builder.class);
    }

    // Construct using io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      value_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.pravega.connectors.flink.formats.registry.testProto.ProtobufTest.internal_static_io_pravega_connectors_flink_formats_registry_testProto_InternalMessage_descriptor;
    }

    @java.lang.Override
    public io.pravega.connectors.flink.formats.registry.testProto.InternalMessage getDefaultInstanceForType() {
      return io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.getDefaultInstance();
    }

    @java.lang.Override
    public io.pravega.connectors.flink.formats.registry.testProto.InternalMessage build() {
      io.pravega.connectors.flink.formats.registry.testProto.InternalMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.pravega.connectors.flink.formats.registry.testProto.InternalMessage buildPartial() {
      io.pravega.connectors.flink.formats.registry.testProto.InternalMessage result = new io.pravega.connectors.flink.formats.registry.testProto.InternalMessage(this);
      result.value_ = value_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.pravega.connectors.flink.formats.registry.testProto.InternalMessage) {
        return mergeFrom((io.pravega.connectors.flink.formats.registry.testProto.InternalMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.pravega.connectors.flink.formats.registry.testProto.InternalMessage other) {
      if (other == io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.getDefaultInstance()) return this;
      if (other.value_ != 0) {
        setValueValue(other.getValueValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.pravega.connectors.flink.formats.registry.testProto.InternalMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.pravega.connectors.flink.formats.registry.testProto.InternalMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int value_ = 0;
    /**
     * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values value = 1;</code>
     * @return The enum numeric value on the wire for value.
     */
    @java.lang.Override public int getValueValue() {
      return value_;
    }
    /**
     * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values value = 1;</code>
     * @param value The enum numeric value on the wire for value to set.
     * @return This builder for chaining.
     */
    public Builder setValueValue(int value) {
      
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values value = 1;</code>
     * @return The value.
     */
    @java.lang.Override
    public io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values getValue() {
      @SuppressWarnings("deprecation")
      io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values result = io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values.valueOf(value_);
      return result == null ? io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values.UNRECOGNIZED : result;
    }
    /**
     * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values value = 1;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      value_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Values value = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      
      value_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.pravega.connectors.flink.formats.registry.testProto.InternalMessage)
  }

  // @@protoc_insertion_point(class_scope:io.pravega.connectors.flink.formats.registry.testProto.InternalMessage)
  private static final io.pravega.connectors.flink.formats.registry.testProto.InternalMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.pravega.connectors.flink.formats.registry.testProto.InternalMessage();
  }

  public static io.pravega.connectors.flink.formats.registry.testProto.InternalMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InternalMessage>
      PARSER = new com.google.protobuf.AbstractParser<InternalMessage>() {
    @java.lang.Override
    public InternalMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InternalMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InternalMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InternalMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.pravega.connectors.flink.formats.registry.testProto.InternalMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

