// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/protobufTest.proto

package io.pravega.connectors.flink.formats.registry.testProto;

public interface Message1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.pravega.connectors.flink.formats.registry.testProto.Message1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage internal = 1;</code>
   * @return Whether the internal field is set.
   */
  boolean hasInternal();
  /**
   * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage internal = 1;</code>
   * @return The internal.
   */
  io.pravega.connectors.flink.formats.registry.testProto.InternalMessage getInternal();
  /**
   * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage internal = 1;</code>
   */
  io.pravega.connectors.flink.formats.registry.testProto.InternalMessageOrBuilder getInternalOrBuilder();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
