// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/protobufTest.proto

package io.pravega.connectors.flink.formats.registry.testProto;

/**
 * Protobuf type {@code io.pravega.connectors.flink.formats.registry.testProto.Message1}
 */
public final class Message1 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.pravega.connectors.flink.formats.registry.testProto.Message1)
    Message1OrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message1.newBuilder() to construct.
  private Message1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message1() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message1();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message1(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Builder subBuilder = null;
            if (internal_ != null) {
              subBuilder = internal_.toBuilder();
            }
            internal_ = input.readMessage(io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(internal_);
              internal_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.pravega.connectors.flink.formats.registry.testProto.ProtobufTest.internal_static_io_pravega_connectors_flink_formats_registry_testProto_Message1_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.pravega.connectors.flink.formats.registry.testProto.ProtobufTest.internal_static_io_pravega_connectors_flink_formats_registry_testProto_Message1_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.pravega.connectors.flink.formats.registry.testProto.Message1.class, io.pravega.connectors.flink.formats.registry.testProto.Message1.Builder.class);
  }

  public static final int INTERNAL_FIELD_NUMBER = 1;
  private io.pravega.connectors.flink.formats.registry.testProto.InternalMessage internal_;
  /**
   * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage internal = 1;</code>
   * @return Whether the internal field is set.
   */
  @java.lang.Override
  public boolean hasInternal() {
    return internal_ != null;
  }
  /**
   * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage internal = 1;</code>
   * @return The internal.
   */
  @java.lang.Override
  public io.pravega.connectors.flink.formats.registry.testProto.InternalMessage getInternal() {
    return internal_ == null ? io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.getDefaultInstance() : internal_;
  }
  /**
   * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage internal = 1;</code>
   */
  @java.lang.Override
  public io.pravega.connectors.flink.formats.registry.testProto.InternalMessageOrBuilder getInternalOrBuilder() {
    return getInternal();
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (internal_ != null) {
      output.writeMessage(1, getInternal());
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (internal_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getInternal());
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.pravega.connectors.flink.formats.registry.testProto.Message1)) {
      return super.equals(obj);
    }
    io.pravega.connectors.flink.formats.registry.testProto.Message1 other = (io.pravega.connectors.flink.formats.registry.testProto.Message1) obj;

    if (hasInternal() != other.hasInternal()) return false;
    if (hasInternal()) {
      if (!getInternal()
          .equals(other.getInternal())) return false;
    }
    if (!getName()
        .equals(other.getName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasInternal()) {
      hash = (37 * hash) + INTERNAL_FIELD_NUMBER;
      hash = (53 * hash) + getInternal().hashCode();
    }
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.pravega.connectors.flink.formats.registry.testProto.Message1 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.Message1 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.Message1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.Message1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.Message1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.Message1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.Message1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.Message1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.Message1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.Message1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.Message1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.pravega.connectors.flink.formats.registry.testProto.Message1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.pravega.connectors.flink.formats.registry.testProto.Message1 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.pravega.connectors.flink.formats.registry.testProto.Message1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.pravega.connectors.flink.formats.registry.testProto.Message1)
      io.pravega.connectors.flink.formats.registry.testProto.Message1OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.pravega.connectors.flink.formats.registry.testProto.ProtobufTest.internal_static_io_pravega_connectors_flink_formats_registry_testProto_Message1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.pravega.connectors.flink.formats.registry.testProto.ProtobufTest.internal_static_io_pravega_connectors_flink_formats_registry_testProto_Message1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.pravega.connectors.flink.formats.registry.testProto.Message1.class, io.pravega.connectors.flink.formats.registry.testProto.Message1.Builder.class);
    }

    // Construct using io.pravega.connectors.flink.formats.registry.testProto.Message1.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (internalBuilder_ == null) {
        internal_ = null;
      } else {
        internal_ = null;
        internalBuilder_ = null;
      }
      name_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.pravega.connectors.flink.formats.registry.testProto.ProtobufTest.internal_static_io_pravega_connectors_flink_formats_registry_testProto_Message1_descriptor;
    }

    @java.lang.Override
    public io.pravega.connectors.flink.formats.registry.testProto.Message1 getDefaultInstanceForType() {
      return io.pravega.connectors.flink.formats.registry.testProto.Message1.getDefaultInstance();
    }

    @java.lang.Override
    public io.pravega.connectors.flink.formats.registry.testProto.Message1 build() {
      io.pravega.connectors.flink.formats.registry.testProto.Message1 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.pravega.connectors.flink.formats.registry.testProto.Message1 buildPartial() {
      io.pravega.connectors.flink.formats.registry.testProto.Message1 result = new io.pravega.connectors.flink.formats.registry.testProto.Message1(this);
      if (internalBuilder_ == null) {
        result.internal_ = internal_;
      } else {
        result.internal_ = internalBuilder_.build();
      }
      result.name_ = name_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.pravega.connectors.flink.formats.registry.testProto.Message1) {
        return mergeFrom((io.pravega.connectors.flink.formats.registry.testProto.Message1)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.pravega.connectors.flink.formats.registry.testProto.Message1 other) {
      if (other == io.pravega.connectors.flink.formats.registry.testProto.Message1.getDefaultInstance()) return this;
      if (other.hasInternal()) {
        mergeInternal(other.getInternal());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.pravega.connectors.flink.formats.registry.testProto.Message1 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.pravega.connectors.flink.formats.registry.testProto.Message1) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.pravega.connectors.flink.formats.registry.testProto.InternalMessage internal_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.pravega.connectors.flink.formats.registry.testProto.InternalMessage, io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Builder, io.pravega.connectors.flink.formats.registry.testProto.InternalMessageOrBuilder> internalBuilder_;
    /**
     * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage internal = 1;</code>
     * @return Whether the internal field is set.
     */
    public boolean hasInternal() {
      return internalBuilder_ != null || internal_ != null;
    }
    /**
     * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage internal = 1;</code>
     * @return The internal.
     */
    public io.pravega.connectors.flink.formats.registry.testProto.InternalMessage getInternal() {
      if (internalBuilder_ == null) {
        return internal_ == null ? io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.getDefaultInstance() : internal_;
      } else {
        return internalBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage internal = 1;</code>
     */
    public Builder setInternal(io.pravega.connectors.flink.formats.registry.testProto.InternalMessage value) {
      if (internalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        internal_ = value;
        onChanged();
      } else {
        internalBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage internal = 1;</code>
     */
    public Builder setInternal(
        io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Builder builderForValue) {
      if (internalBuilder_ == null) {
        internal_ = builderForValue.build();
        onChanged();
      } else {
        internalBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage internal = 1;</code>
     */
    public Builder mergeInternal(io.pravega.connectors.flink.formats.registry.testProto.InternalMessage value) {
      if (internalBuilder_ == null) {
        if (internal_ != null) {
          internal_ =
            io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.newBuilder(internal_).mergeFrom(value).buildPartial();
        } else {
          internal_ = value;
        }
        onChanged();
      } else {
        internalBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage internal = 1;</code>
     */
    public Builder clearInternal() {
      if (internalBuilder_ == null) {
        internal_ = null;
        onChanged();
      } else {
        internal_ = null;
        internalBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage internal = 1;</code>
     */
    public io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Builder getInternalBuilder() {
      
      onChanged();
      return getInternalFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage internal = 1;</code>
     */
    public io.pravega.connectors.flink.formats.registry.testProto.InternalMessageOrBuilder getInternalOrBuilder() {
      if (internalBuilder_ != null) {
        return internalBuilder_.getMessageOrBuilder();
      } else {
        return internal_ == null ?
            io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.getDefaultInstance() : internal_;
      }
    }
    /**
     * <code>.io.pravega.connectors.flink.formats.registry.testProto.InternalMessage internal = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.pravega.connectors.flink.formats.registry.testProto.InternalMessage, io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Builder, io.pravega.connectors.flink.formats.registry.testProto.InternalMessageOrBuilder> 
        getInternalFieldBuilder() {
      if (internalBuilder_ == null) {
        internalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.pravega.connectors.flink.formats.registry.testProto.InternalMessage, io.pravega.connectors.flink.formats.registry.testProto.InternalMessage.Builder, io.pravega.connectors.flink.formats.registry.testProto.InternalMessageOrBuilder>(
                getInternal(),
                getParentForChildren(),
                isClean());
        internal_ = null;
      }
      return internalBuilder_;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.pravega.connectors.flink.formats.registry.testProto.Message1)
  }

  // @@protoc_insertion_point(class_scope:io.pravega.connectors.flink.formats.registry.testProto.Message1)
  private static final io.pravega.connectors.flink.formats.registry.testProto.Message1 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.pravega.connectors.flink.formats.registry.testProto.Message1();
  }

  public static io.pravega.connectors.flink.formats.registry.testProto.Message1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message1>
      PARSER = new com.google.protobuf.AbstractParser<Message1>() {
    @java.lang.Override
    public Message1 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message1(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message1> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message1> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.pravega.connectors.flink.formats.registry.testProto.Message1 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

