// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/oneof.proto

package io.pravega.connectors.flink.formats.registry.testProto;

public interface OneofTestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.pravega.connectors.flink.formats.registry.testProto.OneofTest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 a = 1;</code>
   * @return Whether the a field is set.
   */
  boolean hasA();
  /**
   * <code>int32 a = 1;</code>
   * @return The a.
   */
  int getA();

  /**
   * <code>int32 b = 2;</code>
   * @return Whether the b field is set.
   */
  boolean hasB();
  /**
   * <code>int32 b = 2;</code>
   * @return The b.
   */
  int getB();

  public io.pravega.connectors.flink.formats.registry.testProto.OneofTest.TestOneofCase getTestOneofCase();
}
