// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/protobufTest.proto

package io.pravega.connectors.flink.formats.registry.testProto;

public interface testMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.pravega.connectors.flink.formats.registry.testProto.testMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 field1 = 2;</code>
   * @return The field1.
   */
  int getField1();
}
