/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.pravega.connectors.flink.utils;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SpecificRecordTestClass extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7938247601785509576L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SpecificRecordTestClass\",\"namespace\":\"io.pravega.connectors.flink.utils\",\"fields\":[{\"name\":\"a\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SpecificRecordTestClass> ENCODER =
      new BinaryMessageEncoder<SpecificRecordTestClass>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SpecificRecordTestClass> DECODER =
      new BinaryMessageDecoder<SpecificRecordTestClass>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SpecificRecordTestClass> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SpecificRecordTestClass> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SpecificRecordTestClass> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SpecificRecordTestClass>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SpecificRecordTestClass to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SpecificRecordTestClass from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SpecificRecordTestClass instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SpecificRecordTestClass fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence a;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SpecificRecordTestClass() {}

  /**
   * All-args constructor.
   * @param a The new value for a
   */
  public SpecificRecordTestClass(java.lang.CharSequence a) {
    this.a = a;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return a;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: a = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'a' field.
   * @return The value of the 'a' field.
   */
  public java.lang.CharSequence getA() {
    return a;
  }


  /**
   * Sets the value of the 'a' field.
   * @param value the value to set.
   */
  public void setA(java.lang.CharSequence value) {
    this.a = value;
  }

  /**
   * Creates a new SpecificRecordTestClass RecordBuilder.
   * @return A new SpecificRecordTestClass RecordBuilder
   */
  public static io.pravega.connectors.flink.utils.SpecificRecordTestClass.Builder newBuilder() {
    return new io.pravega.connectors.flink.utils.SpecificRecordTestClass.Builder();
  }

  /**
   * Creates a new SpecificRecordTestClass RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SpecificRecordTestClass RecordBuilder
   */
  public static io.pravega.connectors.flink.utils.SpecificRecordTestClass.Builder newBuilder(io.pravega.connectors.flink.utils.SpecificRecordTestClass.Builder other) {
    if (other == null) {
      return new io.pravega.connectors.flink.utils.SpecificRecordTestClass.Builder();
    } else {
      return new io.pravega.connectors.flink.utils.SpecificRecordTestClass.Builder(other);
    }
  }

  /**
   * Creates a new SpecificRecordTestClass RecordBuilder by copying an existing SpecificRecordTestClass instance.
   * @param other The existing instance to copy.
   * @return A new SpecificRecordTestClass RecordBuilder
   */
  public static io.pravega.connectors.flink.utils.SpecificRecordTestClass.Builder newBuilder(io.pravega.connectors.flink.utils.SpecificRecordTestClass other) {
    if (other == null) {
      return new io.pravega.connectors.flink.utils.SpecificRecordTestClass.Builder();
    } else {
      return new io.pravega.connectors.flink.utils.SpecificRecordTestClass.Builder(other);
    }
  }

  /**
   * RecordBuilder for SpecificRecordTestClass instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SpecificRecordTestClass>
    implements org.apache.avro.data.RecordBuilder<SpecificRecordTestClass> {

    private java.lang.CharSequence a;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.pravega.connectors.flink.utils.SpecificRecordTestClass.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.a)) {
        this.a = data().deepCopy(fields()[0].schema(), other.a);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing SpecificRecordTestClass instance
     * @param other The existing instance to copy.
     */
    private Builder(io.pravega.connectors.flink.utils.SpecificRecordTestClass other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.a)) {
        this.a = data().deepCopy(fields()[0].schema(), other.a);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'a' field.
      * @return The value.
      */
    public java.lang.CharSequence getA() {
      return a;
    }


    /**
      * Sets the value of the 'a' field.
      * @param value The value of 'a'.
      * @return This builder.
      */
    public io.pravega.connectors.flink.utils.SpecificRecordTestClass.Builder setA(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.a = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'a' field has been set.
      * @return True if the 'a' field has been set, false otherwise.
      */
    public boolean hasA() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'a' field.
      * @return This builder.
      */
    public io.pravega.connectors.flink.utils.SpecificRecordTestClass.Builder clearA() {
      a = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SpecificRecordTestClass build() {
      try {
        SpecificRecordTestClass record = new SpecificRecordTestClass();
        record.a = fieldSetFlags()[0] ? this.a : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SpecificRecordTestClass>
    WRITER$ = (org.apache.avro.io.DatumWriter<SpecificRecordTestClass>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SpecificRecordTestClass>
    READER$ = (org.apache.avro.io.DatumReader<SpecificRecordTestClass>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.a);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.a = in.readString(this.a instanceof Utf8 ? (Utf8)this.a : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.a = in.readString(this.a instanceof Utf8 ? (Utf8)this.a : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










