// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneof.proto

package io.pravega.connectors.flink.formats.registry;

public final class Oneof {
  private Oneof() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_pravega_connectors_flink_formats_registry_OneofTest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_pravega_connectors_flink_formats_registry_OneofTest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013oneof.proto\022,io.pravega.connectors.fli" +
      "nk.formats.registry\"3\n\tOneofTest\022\013\n\001a\030\001 " +
      "\001(\005H\000\022\013\n\001b\030\002 \001(\005H\000B\014\n\ntest_oneofB0\n,io.p" +
      "ravega.connectors.flink.formats.registry" +
      "P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_io_pravega_connectors_flink_formats_registry_OneofTest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_pravega_connectors_flink_formats_registry_OneofTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_pravega_connectors_flink_formats_registry_OneofTest_descriptor,
        new java.lang.String[] { "A", "B", "TestOneof", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
