// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneof.proto

package io.pravega.connectors.flink.formats.registry;

public interface OneofTestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.pravega.connectors.flink.formats.registry.OneofTest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 a = 1;</code>
   */
  boolean hasA();
  /**
   * <code>optional int32 a = 1;</code>
   */
  int getA();

  /**
   * <code>optional int32 b = 2;</code>
   */
  boolean hasB();
  /**
   * <code>optional int32 b = 2;</code>
   */
  int getB();

  public io.pravega.connectors.flink.formats.registry.OneofTest.TestOneofCase getTestOneofCase();
}
